### ISSUE TITLE
What does the arg in linux system call signify?

### ISSUE THREAD

**Issue by lokesh411** [pniewiejski/learn-io-polling#4]
It might be a very trivial question, but i didn't find any answers around
The man page of `epoll_wait()` says `epoll_wait(2)` in [here](https://man7.org/linux/man-pages/man2/epoll_wait.2.html#STANDARDS)
What does `2` signify here?

**Comment by pniewiejski** [comment]
Hi,
It’s a reference to Linux manual. 2 stands for system calls. In man pages you will often see this notation in the “see also” section. 

You can look it up here: https://man7.org/linux/man-pages/man1/man.1.html

**Comment by lokesh411** [comment]
Understood, thanks a ton!
